from enum import StrEnum


class RunState(StrEnum):
    WAITING_FOR_DATA = "WAITING_FOR_DATA"
    DOWNLOADING = "DOWNLOADING"
    PROCESSING = "PROCESSING"
    GENERATING_OUTLOOK = "GENERATING_OUTLOOK"
    READY = "READY"
    FAILED = "FAILED"
